apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-batch-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-batch-app
  template:
    metadata:
      labels:
        app: spring-batch-app
    spec:
      containers:
      - name: spring-batch-app
        # host.minikube.internal:5000는 Minikube 내부에서 호스트의 5000포트(Registry)를 가리킵니다.
        image: host.minikube.internal:5000/myapp-spring-batch:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: spring-batch-service
spec:
  selector:
    app: spring-batch-app
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP
